### ISSUE TITLE
Add wear slot BACKPACK

### ISSUE THREAD

**Issue by calvnnhobs** [calvnnhobs/AnturMUD#10]
Add "backpack" eq slot. Maybe just "back"?

**Comment by calvnnhobs** [comment]
http://www.tbamud.com/forum/8-snippets/23-how-to-add-a-wear-slot

**Comment by Exiled0** [comment]
I think I've done this with my latest patch. Things didn't line up perfectly with the tutorial (mainly, tutorial has an extra section in one of the files with a bunch of blank spaces - " " - set aside, which I did not see. I think I covered everything.

**Comment by calvnnhobs** [comment]
Cool, send a new pull request and I can test

**Comment by calvnnhobs** [comment]
I've merged this code in. Checking now

**Comment by calvnnhobs** [comment]
Looking good, now part of AnturMUD!

**Comment by Exiled0** [comment]
My hope is to also have armor (either backplate or a strapped on shield) as an option eventually. But I believe that is just creating new items, and this same code should cover wearing, right?
