### ISSUE TITLE
New wear slot - EARS

### ISSUE THREAD

**Issue by calvnnhobs** [calvnnhobs/AnturMUD#25]
New wear slot - EARS

**Comment by Exiled0** [comment]
Muffs or rings?
Single (pair of), or two?

**Comment by calvnnhobs** [comment]
Earrings usually, muffs possible.

One EARS slot for both ears.

**Comment by Exiled0** [comment]
Should be good to merge.

**Comment by calvnnhobs** [comment]
Looks good. Merged with master, old branch deleted.
